// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lavdmwgremazcnkokxgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdmRtd2dyZW1hemNua29reGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzI3MDAsImV4cCI6MjA3MDYwODcwMH0.78LkZFC_gv8_taAZnDVF84A0BGvPxlWrICpGKLhjvrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});